services:
  - type: web
    name: monitor-linhas-sp-bot
    runtime: python
    repo: https://github.com/SEU_USUARIO/monitor-linhas-sp
    plan: free
    region: oregon
    # branch: main   # Remove esta linha
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: ALERTAR_FALHA
        value: true
