services:
  - type: web
    name: monitor-linhas-sp-bot
    runtime: python
    repo: https://github.com/SEU_USUARIO/monitor-linhas-sp
    plan: free
    region: oregon  # Regiões válidas: oregon, frankfurt, singapore, ohio, virginia
    branch: main    # Verifique se existe esse branch no GitHub
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: ALERTAR_FALHA
        value: true
      - key: MODO_INTERATIVO
        value: true
      - key: PYTHON_VERSION
        value: 3.10.12
